version: 2.1

jobs:

  etsumm:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install pytest sqlalchemy jsonschema unittest-xml-reporting click gitpython jinja2 requests python-dateutil pytest-shutil
      - run: mkdir -p /tmp/artifacts
      - run:
          name: test
          command: cd etsumm && pytest --junitxml=/tmp/artifacts/junit.xml 2>&1 | tee /tmp/artifacts/pytest.out
      - store_test_results:
          path: /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

workflows:

  etsumm-build-and-test:
    jobs:
      - etsumm
